name: fapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  flat_icons_flutter:
  flutter_svg: ^0.22.0
  # google_mobile_ads: ^0.11.0+4 #/////
  google_mobile_ads: ^0.13.4 #/////
  cloud_firestore: ^2.5.1
  firebase_core: ^1.6.0
  auto_animated: ^3.0.0
  flutter_bloc: ^6.1.1
  splash_screen_view: ^3.0.0
  hive: ^2.0.3
  share: ^2.0.4
  google_fonts: ^2.1.0
  sweetalertv2:
  hive_flutter: 
  # flutter_native_admob: ^2.1.0+3

  flutter_native_admob:
    git:
      url:
        https://github.com/hicnar/flutter_native_admob.git
  
splash_screen_view:
  color: "#ffffff"

dev_dependencies:
  build_runner:
  freezed: ^0.12.6
  json_serializable: ^3.5.1
  flutter_test:
    sdk: flutter

  #hive data generators
  hive_generator: 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: greycliff-cf-regular
      fonts:
        - asset: assets/fonts/greycliff-cf-regular.ttf
          weight: 700

    - family: GrechenFuemen-Regular
      fonts:
        - asset: assets/fonts/GrechenFuemen-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
