const FOOD_CATEGORIES = [
  {"name": "Vegetables", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Fruits", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Juices", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Viande", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Milk", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Fish", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Noodels", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Oils", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Cheese", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Cake", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Sausage", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Fast Food", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Burgers", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Cream Glace", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Dessert", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Fries", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Fruits", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Ice Cream", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Salad Cesar", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Sandwich", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Glace", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Milk Shake", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Nuggets", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Sauce", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Wraps", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Burger King Beignet", "imagePath": "assets/images/vegetables.jpg"},
  {"name": "Dominos Pizza", "imagePath": "assets/images/vegetables.jpg"},
];